### ISSUE TITLE
No donation link in README.md

### ISSUE THREAD

**Issue by alexose** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#106]
As a happy user of SSRPARI, I would like to show my appreciation to the hard working author(s).  Is there a place I can donate?

Thanks :)

**Comment by BaReinhard** [comment]
Hey @alexose , this definitely caught me off guard. Not something I ever thought of needing/setting up. I am glad that you like the project. I’ll look into setting up a donation functionality. 


Thanks for bringing it up.

**Comment by BaReinhard** [comment]
added a donation link to the README, feel free to donate, but don't feel obligated. :)
