### ISSUE TITLE
Feature Request: Run script when any playback starts or ends.

### ISSUE THREAD

**Issue by justilew** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#110]
Like Shairport-Sync, it would be great to be able to run a script when any playback starts or ends. I currently use this in Shairport-Sync to turn on and off my amp.

**Comment by BaReinhard** [comment]
This can be easily done on Bluetooth connection/disconnection .use the bluez-udev file in /usr/local/bin . There is some conditional statements for adding and removing the device, placing the proper scripts for your amp in there should work similarly to shairports feature.

**Comment by justilew** [comment]
Oh awesome! Thanks for the tip!

**Comment by BaReinhard** [comment]
no problem!
