### ISSUE TITLE
Running su volumio -c ./bt_pa_config.sh... Failing. 

### ISSUE THREAD

**Issue by Katzekonig** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#120]
> 
> SSRPARI [Sun Mar  4 23:08:18 UTC 2018] Running su volumio -c ./bt_pa_config.sh...
> SSRPARI [Sun Mar  4 23:08:18 UTC 2018] Executing sudo cp usr/local/bin/volume-watcher.py /usr/local/bin/volume-watcher.py
> Fatal error encountered: 'sudo cp usr/local/bin/volume-watcher.py /usr/local/bin/volume-watcher.py' failed
> Fatal error encountered: su volumio -c ./bt_pa_config.sh failed

I've tried to figure out why it's failing but the script is beyond my skill. This is my 2nd try on a fresh install. Thanks. 

Edit: I started the script with this: 

> git clone https://github.com/bareinhard/super-simple-raspberry-pi-audio-receiver-install
> cd super-simple-raspberry-pi-audio-receiver-install
> git checkout volumio-fix
> sudo ./install.sh

One weird thing that I found which you may or may not be aware of, it hung up at this point for a very long time until I pressed enter, unprompted:

> SSRPARI [Sun Mar  4 22:01:49 UTC 2018] Updating via Apt-Get
> SSRPARI [Sun Mar  4 22:02:26 UTC 2018] Upgrading via Apt-Get

**Comment by freakyc** [comment]
I had the same thing and I think it's from using SSH when running it.  I opened bt_pa_config.sh in nano and did a replace on 'sudo' and replaced it with 'sudo -S'.  This will output the prompt to provide your password for sudo to the screen.

The file functions.sh has the 'exc' function and it's sending the output of the commands it's executing to /dev/null.  I mention that in case you're having a separate issue, or it helps someone else with troubleshooting.

**Comment by Katzekonig** [comment]
@freakyc Okay, thanks! That worked. I replaced every instance of `sudo` with `sudo -S` in install.sh, bt_pa_config.sh and removed the calls for `exc` as well and it went through without a hitch!

**Comment by BaReinhard** [comment]
Thanks for this update all! I will look into making this change in the coming weeks.

If anyone would be so kind to make a pull request for this it would be greatly appreciated. Possibly a PR on the volumio branch would be optimal or find a way to use a sudo command function and replace sudo with it and inside the sudo function we could have it check whether its a volumio install or other and use the specified install script for this.

**Comment by freakyc** [comment]
I actually completely missed the mention of volumio.  I had to do the above on an install of Raspbian Stretch.

I imagine this is going to be necessary for any of the scripts called by another script, when the second script uses sudo.  I'll try to dig in to it more and see if I can put something together for a PR.
