### ISSUE TITLE
Project license 

### ISSUE THREAD

**Issue by paulocoutinhox** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#127]
Hi,

Please add the license to your readme to we understand if we can use in comercial projects.

Thanks.

**Comment by BaReinhard** [comment]
Link to the license. https://github.com/BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install/blob/master/LICENSE

Please feel free to use in commercial projects. If your legal team doesn't approve of this license let me know and we can change it to something they approve of.
