### ISSUE TITLE
Installprocess won't finish

### ISSUE THREAD

**Issue by edoveral** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#135]
First of all, thanks for your great work on this plugin. I'm building a volumio based bluetooth radio and this is a great way to achieve my goal.

However, after selecting the 'bluetooth only' option, the process won't get passed 'upgrading via apt-get' step. There is no point where I can select what audiocard I'm using.  Is there something I'm doing wrong or what is the best course of action in this situation? 

I'm new to this and trying to learn.

**Comment by edoveral** [comment]
Problem solved after a fresh install. Tried this before, third time was a charme.

After that some critical errors, after adding -S to all sudo commands I was fine. Got it up and running now with latest Volumio.

**Comment by BaReinhard** [comment]
Glad you got it working. thanks for the information
