### ISSUE TITLE
If you lost wireless and need to re-enable.

### ISSUE THREAD

**Issue by RoninMD69** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#27]
After installing the Super-Simple-Raspberry-Pi-Audio-Receiver-Install, my Raspberry Pi 3 lost wireless connectivity on reboot.  I'm putting this up here so no one else takes too long fixing it.  Bluetooth has a tendency to hiccup while wifi is enabled but there were still a few things things I needed wifi for before using the pi as a car audio receiver.  So:

went to` /etc/dhcpcd.conf` and commented out `denyinterfaces wlan0` with a hashtag (#) 
then reset permissions to writeable and executable for user.

then went to` /etc/network/interfaces`
removed the hashtag (#) from `#allow-hotplug wlan0` and `#iface wlan inet static`
changed `iface wlan inet static` to `iface wlan inet dhcp`
removed the hashtag (#) from `#wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf`

When I'm ready to put it into my car stereo, I'll return the settings or manually disable wifi.

**Comment by BaReinhard** [comment]
Thanks for this! I typically use a RPI2/3 for testing as installation is just quicker so it never occurred to me that one would need to use of wifi after the initial installation process. For the time being ill leave this as an issue. When I get a chance Ill add this to the readme.md
