### ISSUE TITLE
Sporadic audio corruption with Raspi3 

### ISSUE THREAD

**Issue by alexose** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#37]
I've noticed sporadic (and unpredictable) corruption when I'm playing audio via Airplay on a Raspberry Pi 3.  The audio cuts out momentarily, then sounds choppy and robotic for a few seconds before it returns to normal.

I've tried two different Pis, so I highly doubt that it's hardware related.  Possibly related to https://github.com/raspberrypi/linux/issues/1402, but I'm not sure.  I'm making a note of it here while I continue to research what the problem might be.

**Comment by BaReinhard** [comment]
You may want to look at issue #4 I believe it is the same issue you are describing

**Comment by alexose** [comment]
Oops, you're right.  This is a dupe.
