### ISSUE TITLE
missing packages to get it to compile

### ISSUE THREAD

**Issue by thk4711** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#45]
I started with afresh raspbian image and had to manually install the following:
apt-get install intltool
apt-get install libtool
apt-get install libjson-c-dev
apt-get install libsndfile-dev
After that was added it worked.

**Comment by BaReinhard** [comment]
what version of raspbian are you using? Lite or w/ PIXEL?

**Comment by thk4711** [comment]
I am using the Lite version.

**Comment by BaReinhard** [comment]
Sorry for being MIA was this stretch or Jessie? I believe the libjson-c package changed in stretch. We also just made a change to compile libjson-c from the git repo so I also believe this issue should be fixed.
