### ISSUE TITLE
How to send and receive audito via bluetooth

### ISSUE THREAD

**Issue by Khoa-NT** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#46]
Hi,
I don't have much knowledge in bluetooth. Would you mind if I ask some questions ?

1/ Does this project need the usb bluetooth 4.0 ? or run on bluetooth default inside of Raspberry Pi ?
2/ Does this project help connect Bluetooth Headset To Raspberry Pi 3 (A2DP & HSP) / pi zero W ?

After raspberry pi pair with the module, right click the speaker icon on pannel and select the bluetooth audio module.
Then I can send audio from raspberry pi 3 to the bluetooth audio modulle via bluetooth.

But the raspberry pi 3 can't receive the audio from the bluetooth audio modulle.
Currently I can send sound from raspberry pi to my bluetooth module but raspberry pi doesn't receive any sound from it.
I look on the pavucontrol input tab and I can't find source audio from my bluetooth audio module.

What I want is connect raspberry Pi with my bluetooth module. So that Raspberry pi can get input sound from my bluetooth module and send output sound to it.
Does anyone have know how to config raspberry pi to send audio and receive audio via bluetooth ?
If bluetooth inside raspberry pi can't do it, how to config it with usb bluetooth dongle ?

Would you mind helping me ?
Thanks

**Comment by BaReinhard** [comment]
Unfortunately, for the time being this only works on Raspbian Lite, and doesn't work on Raspbian with Pixel or any other Desktop Enviroment. It was originally meant to be headless for quicker boot times. 

However, to answer your questions:
1. This project will use the built-in bluetooth given you are using a Raspberry Pi 3 or Raspberry Pi Zero W 

2. This project is meant to stream audio to the Raspberry Pi to play off of physically connected speakers, it will not play music to bluetooth speakers.
