### ISSUE TITLE
This is not working on RPi2.

### ISSUE THREAD

**Issue by ghost** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#48]
Hi, 

unfortunately, after installation it's not working on RPi 2 with Edimax WiFi card, no soundcard and newest fresh raspbian. I cannot see any rpi-related-wifi-network on my iPhone. I chose option 1 during installation.

**Comment by BaReinhard** [comment]
The version of the board should not matter. I have installed it on a Zero W as well as a 3. The most important part is making sure you are using Raspbian Jessie Lite you can download [here](http://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2017-07-05/). There have been a number of bug fixes in the past week that should solve many of the issues that people were experiencing.
