### ISSUE TITLE
BT Audio not playing

### ISSUE THREAD

**Issue by jefflivid55** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#52]
Hi, I am using a Pi3 with Raspbian Jesse

I run the install script, and after a while the Pi restarts.
I see the normal desktop upon reboot, and the BT symbol is flashing.
I can pair with the Pi from my phone, but when I play audio from my phone it does not play through the Pi.
I have tried HDMI and audio jack.

Other people mentioned Kodi, but I can't see any Kodi installed.

Any help would be greatly appreciated! 

Edit: I chose option 2 for Home Audio, and option 0 for no sound card

**Comment by TheJulianJES** [comment]
I have the same problem.

**Comment by mdEpbH0n86** [comment]
This worked to get audio to play through the audio jack: 
`sudo amixer -c 0 cset numid=3 1`

**Comment by BaReinhard** [comment]
This is because this installation is only meant for Jessie LITE, not w/ Pixel. Kodi only shows when on LITE.

I haven't spent much time trying to get this working on Desktop versions, but  it will likely require some small changes to the /etc/asound.conf file

**Comment by BaReinhard** [comment]
This should now be fixed with the latest master branch. There is also another issue #102 which should work for stretch for those interested.
