### ISSUE TITLE
Support for Mopidy, allows Internet streaming

### ISSUE THREAD

**Issue by arjunmenon** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#61]
Hey
Nice project.
Supporting [Mopidy](https://docs.mopidy.com/en/latest/installation/raspberrypi/#raspberrypi-installation) and [Upmpdcli](https://docs.mopidy.com/en/latest/clients/upnp/) allows for streaming from Spotify, Youtube, Soundcloud, local files, etc and configures Multi room audio, additional. 

Gmediarender would not be required. Shairport would not be required, if music streaming is the sole goal

As an enhancement to AP, [comitup](https://github.com/davesteele/comitup) is very solid. Solves
> Unsure how Android will act on a wireless network without internet, iOS doesn't display the WiFi signals and will use Cellular Data for data requirements. However, iOS devices still can play local music to the Pi without any cellular data.

**Comment by BaReinhard** [comment]
I will definitely have to check out the projects. Ultimately, I believe that a lot of the other functionalities, such as AP, GMEDIA, and Kodi may eventually get moved to a new branch which will still include all of them, but I believe that the main focus will stick with Bluetooth, Airplay, and possibly compiling the latest Kodi. Unfortunately, my time is becoming more and more sparse unless I can get others working on some of the functionality.
