### ISSUE TITLE
How to select soundcard

### ISSUE THREAD

**Issue by pubso** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#63]
I didn't get a list of soundcards during install at the beginning. I want to use USB soundcard. I chose to install Volumio bluetooth only option 4. I can pair my phone with Raspberry, but I can't hear any sound.  Is there a way to select soundcard in config?

**Comment by jkobti** [comment]
same for me, hope someone answers

**Comment by BaReinhard** [comment]
Setting up a sound card is as easy as creating an asound.conf file let me check the source code real quick

**Comment by BaReinhard** [comment]
So the file is /etc/asound.conf and will depend on what the output of your `aplay-l` shows

**Comment by BaReinhard** [comment]
As a default the file should just need



```
pcm.pulse {
    type pulse
    card 1
}
ctl.pulse {
    type pulse
    card 1
}
pcm.!default {
    type hw
    card 1
}
ctl.!default {
    type hw
    card 1
}
```

**Comment by jkobti** [comment]
thanks @BaReinhard

**Comment by BaReinhard** [comment]
No problem, let me know if that works for you.

**Comment by BaReinhard** [comment]
closing as it should be fixed, if not feel free to re open and we can fix this
