### ISSUE TITLE
no sound at all

### ISSUE THREAD

**Issue by jkobti** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#65]
Hi guys, after installing the home version, which didnt work for me, the sound is not working at all.
is there a way to  roll back to previous settings ?

**Comment by BaReinhard** [comment]
Did you select a sound card? There’s no way currently to roll back aside from looking through the source code and making changes manually.

**Comment by BaReinhard** [comment]
Closing, if you have another similar issue you can reopen this. Fortunately, the latest update to the repo should work (given you use the latest raspbian JESSIE LITE) a link it provided in the README.md to download the proper version.
