### ISSUE TITLE
AirPlay speed question

### ISSUE THREAD

**Issue by kirilldobr** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#88]
I see you use shairport-sync as part of your project.
But there was a problem with it - when pausing/playing audio lagged behind. If you was watching YouTube, for example, you experienced an audio lag.
Does your project work similarly or did you solve the syncing issue?

**Comment by BaReinhard** [comment]
Unfortunately, this issue is present in this project as well. Until they are able to find a solution for streaming video & audio, (like an appletv) this issue is likely to be present.

I am assuming that you are watching the video on a iDevice streaming audio to the pi.

The issue stems from the ability of the device to delay video until sound is played on the device. It's doubtful apple would give us that power over our devices.

**Comment by kirilldobr** [comment]
There is a great app called LonelyScreen.
I don't know what magic are they using, but music streaming from iDevice to PC works flawlessly.
And youtube played in sync from MacBook.

**Comment by BaReinhard** [comment]
I had never seen that before. Unfortunately, it looks like it only works on Mac and PC. Unfortunately, it is also a paid service. I don't know enough about avahi or AirPlay to even begin to solve this issue either. Ultimately, this issue is more relevant to shairport-sync's issue location.

**Comment by kirilldobr** [comment]
Looks like it has Sublime-like paying model, but that's behind the question)
Anyway, I will continue testing and write back with the results.

**Comment by BaReinhard** [comment]
This has gotten me curious, I'll continue looking into solutions. How long is the delay between audio and video?
As there is a setting which can be used to correct somewhat small audio delays:
https://github.com/mikebrady/shairport-sync/blob/master/scripts/shairport-sync.conf#L42

**Comment by kirilldobr** [comment]
Just now installed shairport on my Mac and everything is working great. When i pause a video on iPhone and then start it again there is 2.25 second delay in audio and then it catches up and syncs perfectly, as explained here:
https://github.com/mikebrady/shairport-sync#synchronisation-latency-stuffing

Now I'll try to install it to raspberry again and report back. Maybe I had an old shairport version or something.

**Comment by kirilldobr** [comment]
Yep, I was right!
I was installing shairport from some 7 year old repository. Installing the last version removed all my issues.

**Comment by BaReinhard** [comment]
Awesome! Glad the updated version works for you!

**Comment by kirilldobr** [comment]
Do you how to stream audio from windows pc to raspberry? It may be over a network or with extra hardware, just anything. With as much latency as possible, of course.

**Comment by BaReinhard** [comment]
Either airfoil for windows or tuneblade
