### ISSUE TITLE
apt-get: show output during installation process and allow user interaction with apt-get / dpkg

### ISSUE THREAD

**Issue by ifs-net** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#91]
updating a raspberry system might take a long time. Maybe you want to add an option to show the output of apt-get during your install.sh
Otherwise it's like a "black box", you cannot see any progress of the installation routine.

My problem was that apt-get dist-upgrade needed some interaction and this broke the installation routine, the process "hanged up"...

**Comment by BaReinhard** [comment]
You bring up a good point. I haven’t needed it on any jessie install but doesn’t mean it isn’t needed. I’ll look into this.

**Comment by BaReinhard** [comment]
A current work around for this is in the `dependencies.sh` change the install command and remove the -qq except for the -y and go to the `functions.sh` and in the function apt_install, remove ’&> /dev/null’ after INSTALL_COMMAND, this will show all the dpkg output.
