### ISSUE TITLE
Unable to find libltdl version 2 during pulseaudio build

### ISSUE THREAD

**Issue by nilayp** [BaReinhard/Super-Simple-Raspberry-Pi-Audio-Receiver-Install#95]
I cloned the latest SSRPARI as of 1/1/2018 and installed Airport, Bluetooth and Soundcard. During the pulseaudio build, in the bootstrap phase, I experienced this error due to a missing dependency:
```
Unable to find libltdl version 2. Makes sure you have libtool 2.4 or later installed.
```
And then it failed. I was able to install the missing dependency using the command below, and restarted the SSRPARI installer (I love that you can do this repeatedly now!) ... and it worked.

To install the missing dependency, execute this command:
```
sudo apt-get install libltdl-dev
```

I have a RPI3 with Hifiberry Digi+ sound card.

Hopefully this will be helpful to someone out there.

-- Nilay

**Comment by BaReinhard** [comment]
I’ll add it now to the dependencies list. Thanks nilay
